=== dgo42/jtg/trunk/java/jtg/jtg.test/src/main/schema/schema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:tns="http://edgo.org" 
	xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	targetNamespace="http://edgo.org"
	elementFormDefault="qualified">
	<xs:element name="DirectUseElement" type="tns:DirectUseElement" />
	<xs:complexType name="DirectUseElement">
		<xs:sequence>
			<xs:element name="EmployeeElement" type="tns:EmployeeElement" nillable="true" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="EmployeeElement">
		<xs:sequence>
			<xs:element name="FirstName" type="xs:string" minOccurs="0" />
			<xs:element name="LastName" type="xs:string" minOccurs="0" />
			<xs:element name="Title" type="xs:string" minOccurs="0" />
		</xs:sequence>
		<xs:attribute name="ID" type="xs:int" />
	</xs:complexType>
</xs:schema>

=== dgo42/jtg/java/jtg/jtg.test/src/main/schema/project.xml
<?xml version="1.0" encoding="utf-8"?>
<tns:DirectUseElement xmlns="http://edgo.org"
	xmlns:tns="http://edgo.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://edgo.org schema.xsd">
	<EmployeeElement ID="0">
		<FirstName>Max</FirstName>
		<LastName>Mustermann</LastName>
		<Title>Herr</Title>
	</EmployeeElement>
	<EmployeeElement ID="1">
		<FirstName>Michael</FirstName>
		<LastName>Schumacher</LastName>
		<Title>Herr</Title>
	</EmployeeElement>
	<EmployeeElement ID="2">
		<FirstName>John</FirstName>
		<LastName>Smidth</LastName>
		<Title>Herr</Title>
	</EmployeeElement>
</tns:DirectUseElement>
